Use Registro
--Procedimientos Almacenados

 GO
 CREATE PROC SP_CREARU_SUARIO --NUEVO USUARIO
 @NAME NVARCHAR(40),
 @LASTNAME NVARCHAR(50),
 @BIRTHDATE DATE,
 @USERNAME NVARCHAR(20),
 @PASSWORD NVARCHAR(100),
 @USERTYPE NVARCHAR(15)
 AS
 INSERT INTO Users 
 VALUES (@NAME,@LASTNAME,@BIRTHDATE,@USERNAME,@PASSWORD,@USERTYPE)


 GO
 CREATE PROC SP_CONSULTAR_USUARIO --CONSULTAR USUARIO
 @USERNAME NVARCHAR(20)
 AS
 SELECT * FROM Users 
 WHERE USERNAME = @USERNAME



 GO
 CREATE PROC SP_CREAR_EDIFICIO --CREAR EDIFICIO
 @NOMBRE NVARCHAR(50)
 AS
 INSERT INTO Edificios 
 VALUES(@NOMBRE)



 GO
 CREATE PROC SP_LISTAR_EDIFICIOS --LISTAR EDIFICIOS
 @NOMBRE NVARCHAR(50)
 AS
 SELECT * FROM Edificios 
 WHERE nombre LIKE '%'+@NOMBRE+'%'


 GO
 CREATE PROC SP_LISTAR_EDIFICIO_POR_ID --LISTAR EDIFICIOS POR ID
 @ID INT
 AS
 SELECT * FROM Edificios 
 WHERE id_edificio = @ID


 GO
 CREATE PROC SP_ELIMINAR_EDIFICIO --ELIMINAR EDIFICIOS
 @ID INT
 AS
 DELETE Edificios
 WHERE id_edificio = @ID


 GO
 CREATE PROC SP_ACTUALIZAR_EDIFICIO --ACTUALIZAR EDIFICIO
 @ID INT,
 @NOMBRE NVARCHAR(50)
 AS
 UPDATE Edificios
 SET
 nombre = @NOMBRE
 WHERE id_edificio = @ID


 GO
 CREATE PROC SP_CREAR_AULA --CREAR AULA
 @NOMBRE NVARCHAR(50),
 @IDEDIFICIO INT
 AS
 INSERT INTO Aulas 
 VALUES(@IDEDIFICIO,@NOMBRE)


 GO
 CREATE PROC SP_LISTAR_AULA --LISTAR AULAS
 @BUSCAR NVARCHAR(50)
 AS
 SELECT * FROM Aulas 
 WHERE nombre LIKE '%'+@BUSCAR+'%'

 GO
 CREATE PROC SP_LISTAR_AULA_POR_EDIFICIO  --LISTAR AULAS POR EDIFICIO
 @ID NVARCHAR(50)
 AS
 SELECT * FROM Aulas 
 WHERE id_edificio = @ID


 GO
 CREATE PROC SP_ELIMINAR_AULA --ELIMINAR AULAS
 @ID INT
 AS
 DELETE Aulas
 WHERE id_aula = @ID

 GO
 CREATE PROC SP_ACTUALIZAR_AULA --ACTUALIZAR AULAS
 @ID INT,
 @IDEDIFICIO INT,
 @NOMBRE NVARCHAR(50)
 AS
 UPDATE Aulas
 SET
 id_edificio = @IDEDIFICIO,
 nombre = @NOMBRE
 WHERE id_aula = @ID


 GO
 CREATE PROC SP_CREAR_VISITA --CREAR VISITA
 @NOMBRE NVARCHAR(35),
 @APELLIDO NVARCHAR(40),
 @CARRERA NVARCHAR(60),
 @CORREO NVARCHAR(125),
 @IDEDIFICIO INT,
 @H_ENTRADA TIME,
 @H_SALIDA TIME,
 @MOVIVOV NVARCHAR(100),
 @IDAULA INT
 AS
 INSERT INTO Visitas
 VALUES(@NOMBRE,@APELLIDO,@CARRERA,@CORREO,@IDEDIFICIO,@H_ENTRADA,@H_SALIDA,@MOVIVOV,@IDAULA)


 GO
 CREATE PROC SP_LISTAR_VISITA  --LISTAR visitas
 @BUSCAR NVARCHAR(50)
 AS
 SELECT * FROM Visitas 
 WHERE nombre LIKE '%'+@BUSCAR+'%'

GO
CREATE PROC SP_LISTAR_VISITA_EDIFICIO  --LISTAR visitas por edificio
@BUSCAR INT
AS
SELECT * FROM Visitas 
WHERE id_edificio = @BUSCAR


 /*
 --ELIMINAR visitas
 GO
 CREATE PROC SP_ELIMINAR_Visita
 @ID INT
 AS
 DELETE Visitas
 WHERE ID_visita = @ID

 --ACTUALIZAR AULAS
 GO
 CREATE PROC SP_ACTUALIZAR_AULA
 @ID INT,
 @IDEDIFICIO INT,
 @NOMBRE NVARCHAR(50)
 AS
 UPDATE Aulas
 SET
 id_edificio = @IDEDIFICIO,
 nombre = @NOMBRE
 WHERE id_aula = @ID
 */